baseurl: ""
lang: en-ZA

image: /social_916x509.jpg
twitter:
  card: summary_large_image

title: The Bond Cellar - Expert in Bond Origination & Home Loans in Durban, KZN
email: admin@thebondcellar.co.za
email_display: mailto:admin@thebondcellar.co.za
description: "Need help securing your home loan in Durban or KZN? The Bond Cellar is a trusted bond origination specialist serving clients across KwaZulu-Natal. We simplify the mortgage process by comparing offers from multiple lenders, handling paperwork, and fighting for your best interest rate. Whether you're buying your first home, investing in property, or refinancing, we guide you through every step - from pre-approval to keys in hand. Our team knows the local market inside out and works directly with major banks to get your bond approved faster."
author: Eben Roux / Pieter Oosthuizen

analytics:
  google: G-XXX

collections:
  portfolio:

markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

webserver_headers:
  - - Access-Control-Allow-Origin
    - "*"
  - - Access-Control-Allow-Methods
    - GET, OPTIONS, HEAD

logo: /assets/img/logo/the-bond-cellar-logo.jpg

exclude: [node_modules, webpack-config.js, package.json, package-lock.json]

group: The Bond Cellar

company: The Bond Cellar

url: https://thebondcellar.co.za

address: Shop 2, Salamanca Centre, 39 Maryvale Road, Dawncliffe, 3629
telephone: "+27-84-686-6089"
area_served:
  - Durban
  - KwaZulu-Natal
  - South Africa
same_as:
  - https://www.instagram.com/thebondcellar
  - https://www.facebook.com/share/1JhkGPsDmv/
